### ISSUE TITLE
Optical flow

### ISSUE THREAD

**Issue by TiagoShen** [haleqiu/tartanair-shibuya#2]
Hi,
Thank you for providing this dataset. Could you also provide the groundtruth optical flow like the original TartanAir dataset?

**Comment by haleqiu** [comment]
Hi @TiagoShen We don't have the gt data for the optical flow. Just out of curiosity, why do you need the optical flow?

**Comment by TiagoShen** [comment]
Hi @haleqiu, thanks for your reply. What we need are ground truth point (2D or 3D doesn't matter) correspondences, especially for the deformable objects (pedestrains in your case).

**Comment by haleqiu** [comment]
I see. The deformable object is an interesting topic. We will discuss this in our next release. Thank you @TiagoShen for pointing it out.
