### ISSUE TITLE
The real image height is 360 rather than 480.

### ISSUE THREAD

**Issue by g-ch** [haleqiu/tartanair-shibuya#3]
Hi, I found that the real image height is 360 rather than 480. Maybe the document is wrong.

**Comment by haleqiu** [comment]
Yes, there is a mistake. Thank you for pointing it out.

**Comment by haleqiu** [comment]
@g-ch Thank you for pointing this out. The config file has been updated. The FOV of tartan air Shibuya is different from tartan air. The focal length is also updated.
