### ISSUE TITLE
The link to the dataset is not working

### ISSUE THREAD

**Issue by DanRos22** [haleqiu/tartanair-shibuya#5]
https://tartanair.blob.core.windows.net/tartanvo/data/TartanAir_shibuya.zip is not working

**Comment by haleqiu** [comment]
@DanRos22  Thank you for pointing it out, we just renew the download link. Please let me know if there is any further issues. Thanks.

**Comment by DanRos22** [comment]
Hi @haleqiu, 
The new link seems to be not valid. can you check it, please?
Thanks!

**Comment by haleqiu** [comment]
@DanRos22 I just double-checked the link. It works fine. Could you provide more information?

**Comment by DanRos22** [comment]
@haleqiu, 
sorry. my mistake.
Thanks!

**Comment by dd2252** [comment]
Hello -- I am trying the link and it doesn't seem to be working. Would you mind please checking again?

**Comment by haleqiu** [comment]
@dd2252 

Try this google drive:

https://drive.google.com/file/d/1FXsh8ZN-_ngYQQnqloJanSX8bSmq5uJ4/view?usp=sharing

**Comment by dd2252** [comment]
Worked, thank you!
