### ISSUE TITLE
num of keypoint in alpha pose

### ISSUE THREAD

**Issue by colin-de** [haleqiu/tartanair-shibuya#7]
hi!, i noticed the alpha pose has 17 detected point as result, but in the dataset, there are 18 points, could you please let me know how to get the same result as in dataset?

**Comment by haleqiu** [comment]
@colin-de Hi, Did you solve this problem?

**Comment by colin-de** [comment]
Hi, thanks for the reply, I was thinking the 18 keypoints of the dataset could be generated from [https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/output.md]() by setting `--format cmu` is that correct?

**Comment by haleqiu** [comment]
@colin-de Sorry for lateness, I think we follow a similar pattern with the cmu openpose.
